name: heads-up-actions
run-name: ${{ github.actor }} is learning GitHub Actions
define: &app-dir './heads-up'
on: [push]
defaults:
  run:
    working-directory: ./heads-up
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v4
              with:
                node-version: '20'
            - name: Install dependencies
              run: npm ci
            - name: Build
              # runs vite build - generated files live in './dist' which is ignored by git
              run: npm run build
            - name: Upload production-ready build files
              # zips the files in the provided path
              uses: actions/upload-artifact@v4
              with:
                name: dist-files
                path: ./heads-up/dist
            - name: List
              run: ls -R ./dist

    deploy:
        needs: build
        runs-on: ubuntu-latest
        if: github.ref == 'refs/heads/main'
        steps:
          - name: Download artifact
            uses: actions/download-artifact@v4
            with:
              name: dist-files
              path: ./heads-up/dist
          - name: List
            run: ls -R ./dist
          - name: Deploy to GitHub Pages
            uses: peaceiris/actions-gh-pages@v4
            with:
                github_token: ${{ secrets.GITHUB_TOKEN }}
                publish_branch: main
                publish_dir: ./heads-up/pages
